# This is a basic workflow to help you get started with Actions

name: Docker Build and Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Docker image
      run: docker build -t imagechatbot .

    - name: Run Docker container (optional)
      run: docker run imagechatbot

    - name: Push Docker image to registry (optional)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        image: timane/imagechatbot:latest
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Execute Python scripts in Docker container
      run: docker run imagechatbot python /app/preprocess.py

    - name: Execute training script
      run: docker run imagechatbot python /app/train_model.py

    - name: Execute prediction script (optional)
      run: docker run imagechatbot python /app/predict_response.py

    - name: Clean up
      run: docker system prune --force
